//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_EMSEntities : DbContext
    {
        public db_EMSEntities()
            : base("name=db_EMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tb_employee> tb_employee { get; set; }
        public virtual DbSet<tb_PDic> tb_PDic { get; set; }
        public virtual DbSet<tb_stock> tb_stock { get; set; }
        public virtual DbSet<tb_units> tb_units { get; set; }
        public virtual DbSet<tb_currentaccount> tb_currentaccount { get; set; }
        public virtual DbSet<tb_power> tb_power { get; set; }
        public virtual DbSet<tb_resell_detailed> tb_resell_detailed { get; set; }
        public virtual DbSet<tb_resell_main> tb_resell_main { get; set; }
        public virtual DbSet<tb_rewarehouse_detailed> tb_rewarehouse_detailed { get; set; }
        public virtual DbSet<tb_rewarehouse_main> tb_rewarehouse_main { get; set; }
        public virtual DbSet<tb_sell_detailed> tb_sell_detailed { get; set; }
        public virtual DbSet<tb_sell_main> tb_sell_main { get; set; }
        public virtual DbSet<tb_unit> tb_unit { get; set; }
        public virtual DbSet<tb_warehouse_detailed> tb_warehouse_detailed { get; set; }
        public virtual DbSet<tb_warehouse_main> tb_warehouse_main { get; set; }
    }
}
