//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_power
    {
        public int ID { get; set; }
        public string sysuser { get; set; }
        public string password { get; set; }
        public Nullable<bool> stock { get; set; }
        public Nullable<bool> vendition { get; set; }
        public Nullable<bool> storage { get; set; }
        public Nullable<bool> system { get; set; }
        public Nullable<bool> @base { get; set; }
    }
}
