//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_stock()
        {
            this.tb_resell_detailed = new HashSet<tb_resell_detailed>();
            this.tb_rewarehouse_detailed = new HashSet<tb_rewarehouse_detailed>();
            this.tb_sell_detailed = new HashSet<tb_sell_detailed>();
            this.tb_warehouse_detailed = new HashSet<tb_warehouse_detailed>();
        }
    
        public string tradecode { get; set; }
        public string fullname { get; set; }
        public string type { get; set; }
        public string standard { get; set; }
        public string unit { get; set; }
        public string produce { get; set; }
        public Nullable<double> qty { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> averageprice { get; set; }
        public Nullable<double> saleprice { get; set; }
        public Nullable<double> stockcheck { get; set; }
        public Nullable<int> upperlimit { get; set; }
        public Nullable<int> lowerlimit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_resell_detailed> tb_resell_detailed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_rewarehouse_detailed> tb_rewarehouse_detailed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_sell_detailed> tb_sell_detailed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_warehouse_detailed> tb_warehouse_detailed { get; set; }
    }
}
